#ifndef LANGUAGES_ENUM_H
#define LANGUAGES_ENUM_H

enum Languages
{
	English,
	Ukrainian
};

#define MESSAGE_DEFAULT_DEFAULT_SELECT "select please"
#define MESSAGE_DEFAULT_DEFAULT_OPTION "option"
#define MESSAGE_DEFAULT_DEFAULT_INVALIDOPTION "invalid option"

#define MESSAGE_DEFAULT_LANGUAGESELECTION "select the language"
#define MESSAGE_DEFAULT_LANGUAGESELECTION_FORSELECTING "languages list"
#define MESSAGE_DEFAULT_REGISTRATION "registration and login manu"
#define MESSAGE_DEFAULT_REGISTRATION_FORSELECTING "log in and sign in (list to-do)"

// ENGLISH
#define MESSAGE_ENGLISH_DEFAULT_SELECT "Select please"
#define MESSAGE_ENGLISH_DEFAULT_OPTION "Option: "
#define MESSAGE_ENGLISH_DEFAULT_INVALIDOPTION "Invalid option!"

#define MESSAGE_ENGLISH_LANGUAGESELECTION "SELECT THE LANGUAGE"
#define MESSAGE_ENGLISH_LANGUAGESELECTION_FORSELECTING "1. English\n2.Ukrainian"
#define MESSAGE_ENGLISH_REGISTRATION_SIGNIN "SIGNIN"
#define MESSAGE_ENGLISH_REGISTRATION_LOGIN "LOGIN"
#define MESSAGE_ENGLISH_DEFAULT_REGISTRATION_FORSELECTING "1. Sign in\n2. Log in\n3. Exit the program"

// UKRAINIAN
#define MESSAGE_UKRAINIAN_DEFAULT_SELECT "Будь ласка, оберiть"
#define MESSAGE_UKRAINIAN_DEFAULT_OPTION "Вибiр: "
#define MESSAGE_UKRAINIAN_DEFAULT_INVALIDOPTION "Не правильний вибiр!"

#define MESSAGE_UKRAINIAN_LANGUAGESELECTION "ОБЕРIТЬ МОВУ"
#define MESSAGE_UKRAINIAN_LANGUAGESELECTION_FORSELECTING "1. Ангiйська\n2. Українська"
#define MESSAGE_UKRAINIAN_REGISTRATION_SIGNIN "ЗАРЕЄСТРУВАТИСЯ"
#define MESSAGE_UKRAINIAN_REGISTRATION_LOGIN "УВIЙТИ"
#define MESSAGE_UKRAINIAN_DEFAULT_REGISTRATION_FORSELECTING "1. Зареєструватися\n2. Увiйти\n3. Вийти з програми"

// ERRORS
#define LANGUAGE_ERROR "Language error!"
#define TRANSLATION_ERROR "Translation error!"

#endif